### 1. Import the required libararies

In [131]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

In [25]:
# Configure the Display Settings

pd.set_option('display.max_rows', 100)
pd.set_option('display.max_columns', 100)
pd.set_option('display.width', 1000)

### 2. Read the data

In [26]:
train_data = pd.read_csv("mobile_price_classifier_data.csv")
print("The shape of the data is : ", train_data.shape)
train_data.head()

The shape of the data is :  (2000, 21)


battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  m_dep  mobile_wt  n_cores  pc  px_height  px_width   ram  sc_h  sc_w  talk_time  three_g  touch_screen  wifi  price_range
0            842     0          2.2         0   1       0           7    0.6        188        2   2         20       756  2549     9     7         19        0             0     1            1
1           1021     1          0.5         1   0       1          53    0.7        136        3   6        905      1988  2631    17     3          7        1             1     0            2
2            563     1          0.5         1   2       1          41    0.9        145        5   6       1263      1716  2603    11     2          9        1             1     0            2
3            615     1          2.5         0   0       0          10    0.8        131        6   9       1216      1786  2769    16     8         11        1             0     0            2
4           1821     1          1.2         0  13       1          44    0.6        141        2  14       1208      1212  1411     8     2         15        1             1     0            1

In [27]:
# Checking the Data Type of the features

print("The data types of the features is : ", train_data.dtypes)

The data types of the features is :  battery_power      int64
blue               int64
clock_speed      float64
dual_sim           int64
fc                 int64
four_g             int64
int_memory         int64
m_dep            float64
mobile_wt          int64
n_cores            int64
pc                 int64
px_height          int64
px_width           int64
ram                int64
sc_h               int64
sc_w               int64
talk_time          int64
three_g            int64
touch_screen       int64
wifi               int64
price_range        int64
dtype: object


In [28]:
# Looking for any nulls

train_data.isnull().sum()

battery_power    0
blue             0
clock_speed      0
dual_sim         0
fc               0
four_g           0
int_memory       0
m_dep            0
mobile_wt        0
n_cores          0
pc               0
px_height        0
px_width         0
ram              0
sc_h             0
sc_w             0
talk_time        0
three_g          0
touch_screen     0
wifi             0
price_range      0
dtype: int64

In [123]:
data = train_data.copy()

### 3. Scaling and Normalizing  the Data

In [122]:
from sklearn.preprocessing import normalize
from sklearn.preprocessing import scale

In [126]:
x = data.drop("price_range", axis = 1)
y = data["price_range"]
cols = x.columns
x.head()

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  m_dep  mobile_wt  n_cores  pc  px_height  px_width   ram  sc_h  sc_w  talk_time  three_g  touch_screen  wifi
0            842     0          2.2         0   1       0           7    0.6        188        2   2         20       756  2549     9     7         19        0             0     1
1           1021     1          0.5         1   0       1          53    0.7        136        3   6        905      1988  2631    17     3          7        1             1     0
2            563     1          0.5         1   2       1          41    0.9        145        5   6       1263      1716  2603    11     2          9        1             1     0
3            615     1          2.5         0   0       0          10    0.8        131        6   9       1216      1786  2769    16     8         11        1             0     0
4           1821     1          1.2         0  13       1          44    0.6        141        2  14       1208      1212  1411     8     2         15        1             1     0

In [132]:
x_scale = pd.DataFrame(scale(x))
x_scale.columns = cols
x_scale.head()

battery_power      blue  clock_speed  dual_sim        fc    four_g  int_memory     m_dep  mobile_wt   n_cores        pc  px_height  px_width       ram      sc_h      sc_w  talk_time   three_g  touch_screen      wifi
0      -0.902597 -0.990050     0.830779 -1.019184 -0.762495 -1.043966   -1.380644  0.340740   1.349249 -1.101971 -1.305750  -1.408949 -1.146784  0.391703 -0.784983  0.283103   1.462493 -1.786861     -1.006018  0.986097
1      -0.495139  1.010051    -1.253064  0.981177 -0.992890  0.957886    1.155024  0.687548  -0.120059 -0.664768 -0.645989   0.585778  1.704465  0.467317  1.114266 -0.635317  -0.734267  0.559641      0.994018 -1.014099
2      -1.537686  1.010051    -1.253064  0.981177 -0.532099  0.957886    0.493546  1.381165   0.134244  0.209639 -0.645989   1.392684  1.074968  0.441498 -0.310171 -0.864922  -0.368140  0.559641      0.994018 -1.014099
3      -1.419319  1.010051     1.198517 -1.019184 -0.992890 -1.043966   -1.215274  1.034357  -0.261339  0.646842 -0.151168   1.286750  1.236971  0.594569  0.876859  0.512708  -0.002014  0.559641     -1.006018 -1.014099
4       1.325906  1.010051    -0.395011 -1.019184  2.002254  0.957886    0.658915  0.340740   0.021220 -1.101971  0.673534   1.268718 -0.091452 -0.657666 -1.022389 -0.864922   0.730240  0.559641      0.994018 -1.014099

In [133]:
x_norm = pd.DataFrame(normalize(x_scale))
x_norm.columns = cols
x_norm.head()

battery_power      blue  clock_speed  dual_sim        fc    four_g  int_memory     m_dep  mobile_wt   n_cores        pc  px_height  px_width       ram      sc_h      sc_w  talk_time   three_g  touch_screen      wifi
0      -0.186496 -0.204565     0.171657 -0.210585 -0.157548 -0.215706   -0.285270  0.070404   0.278784 -0.227691 -0.269796  -0.291119 -0.236950  0.080934 -0.162194  0.058495   0.302182 -0.369204     -0.207865  0.203749
1      -0.122405  0.249698    -0.309774  0.242560 -0.245455  0.236802    0.285537  0.169971  -0.029680 -0.164339 -0.159697   0.144812  0.421366  0.115527  0.275461 -0.157058  -0.181520  0.138350      0.245734 -0.250698
2      -0.380305  0.249809    -0.309912  0.242668 -0.131600  0.236907    0.122065  0.341594   0.033202  0.051849 -0.159768   0.344443  0.265864  0.109193 -0.076712 -0.213915  -0.091050  0.138412      0.245843 -0.250810
3      -0.338638  0.240990     0.285956 -0.243169 -0.236896 -0.249082   -0.289954  0.246789  -0.062353  0.154331 -0.036067   0.307008  0.295131  0.141859  0.209212  0.122328  -0.000480  0.133526     -0.240028 -0.241956
4       0.314049  0.239236    -0.093561 -0.241400  0.474246  0.226881    0.156068  0.080706   0.005026 -0.261008  0.159530   0.300503 -0.021661 -0.155772 -0.242159 -0.204862   0.172962  0.132554      0.235439 -0.240195

In [172]:
print(y.unique().tolist())

[1, 2, 3, 0]


### 4. Selecting the top 10 features for modelling

In [136]:
from sklearn.ensemble import ExtraTreesClassifier

In [137]:
model = ExtraTreesClassifier()
model

ExtraTreesClassifier(bootstrap=False, class_weight=None, criterion='gini',
           max_depth=None, max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators='warn', n_jobs=None,
           oob_score=False, random_state=None, verbose=0, warm_start=False)

In [138]:
model.fit( x_norm, y)
print ( model.feature_importances_)

[0.06224476 0.02767387 0.02950197 0.02665871 0.02608447 0.03039953
 0.02727098 0.03040862 0.03074275 0.02735503 0.02918982 0.04388287
 0.04160657 0.39835686 0.02754208 0.02619907 0.02783836 0.03125136
 0.02724199 0.02855031]


In [139]:
scores = pd.Series( model.feature_importances_ , index = x_norm.columns).sort_values ( ascending = False)
scores

ram              0.398357
battery_power    0.062245
px_height        0.043883
px_width         0.041607
three_g          0.031251
mobile_wt        0.030743
m_dep            0.030409
four_g           0.030400
clock_speed      0.029502
pc               0.029190
wifi             0.028550
talk_time        0.027838
blue             0.027674
sc_h             0.027542
n_cores          0.027355
int_memory       0.027271
touch_screen     0.027242
dual_sim         0.026659
sc_w             0.026199
fc               0.026084
dtype: float64

In [140]:
top_features = scores.index.tolist()
top_features

['ram',
 'battery_power',
 'px_height',
 'px_width',
 'three_g',
 'mobile_wt',
 'm_dep',
 'four_g',
 'clock_speed',
 'pc',
 'wifi',
 'talk_time',
 'blue',
 'sc_h',
 'n_cores',
 'int_memory',
 'touch_screen',
 'dual_sim',
 'sc_w',
 'fc']

In [141]:
x_sorted = x_norm[top_features]
x_sorted.head()

ram  battery_power  px_height  px_width   three_g  mobile_wt     m_dep    four_g  clock_speed        pc      wifi  talk_time      blue      sc_h   n_cores  int_memory  touch_screen  dual_sim      sc_w        fc
0  0.080934      -0.186496  -0.291119 -0.236950 -0.369204   0.278784  0.070404 -0.215706     0.171657 -0.269796  0.203749   0.302182 -0.204565 -0.162194 -0.227691   -0.285270     -0.207865 -0.210585  0.058495 -0.157548
1  0.115527      -0.122405   0.144812  0.421366  0.138350  -0.029680  0.169971  0.236802    -0.309774 -0.159697 -0.250698  -0.181520  0.249698  0.275461 -0.164339    0.285537      0.245734  0.242560 -0.157058 -0.245455
2  0.109193      -0.380305   0.344443  0.265864  0.138412   0.033202  0.341594  0.236907    -0.309912 -0.159768 -0.250810  -0.091050  0.249809 -0.076712  0.051849    0.122065      0.245843  0.242668 -0.213915 -0.131600
3  0.141859      -0.338638   0.307008  0.295131  0.133526  -0.062353  0.246789 -0.249082     0.285956 -0.036067 -0.241956  -0.000480  0.240990  0.209212  0.154331   -0.289954     -0.240028 -0.243169  0.122328 -0.236896
4 -0.155772       0.314049   0.300503 -0.021661  0.132554   0.005026  0.080706  0.226881    -0.093561  0.159530 -0.240195   0.172962  0.239236 -0.242159 -0.261008    0.156068      0.235439 -0.241400 -0.204862  0.474246

In [142]:
x_top_ten = x_sorted.iloc[:,:10]
x_top_ten.head()

ram  battery_power  px_height  px_width   three_g  mobile_wt     m_dep    four_g  clock_speed        pc
0  0.080934      -0.186496  -0.291119 -0.236950 -0.369204   0.278784  0.070404 -0.215706     0.171657 -0.269796
1  0.115527      -0.122405   0.144812  0.421366  0.138350  -0.029680  0.169971  0.236802    -0.309774 -0.159697
2  0.109193      -0.380305   0.344443  0.265864  0.138412   0.033202  0.341594  0.236907    -0.309912 -0.159768
3  0.141859      -0.338638   0.307008  0.295131  0.133526  -0.062353  0.246789 -0.249082     0.285956 -0.036067
4 -0.155772       0.314049   0.300503 -0.021661  0.132554   0.005026  0.080706  0.226881    -0.093561  0.159530

In [143]:
y.head()

0    1
1    2
2    2
3    2
4    1
Name: price_range, dtype: int64

In [144]:
y.unique().tolist()

[1, 2, 3, 0]

### 5. Splitting the data to train and test

In [146]:
from sklearn.model_selection import train_test_split

In [147]:
x_train, x_test, y_train, y_test = train_test_split(x_top_ten, y , test_size = 0.3, stratify = y)

### 6. Fitting the Decision Tree Classifier

In [148]:
from sklearn.tree import DecisionTreeClassifier

In [149]:
ctree = DecisionTreeClassifier(max_depth= 4)
ctree

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=4,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [150]:
ctree.fit(x_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=4,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [151]:
y_pred  =  ctree.predict(x_test)

In [152]:
# Import the libraries required for calculating the metrics

In [153]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [154]:
print("The accuracy score is : ", accuracy_score ( y_test, y_pred))

The accuracy score is :  0.7833333333333333


In [155]:
print("The Confusion Matrix is : \n\n", confusion_matrix ( y_test, y_pred))

The Confusion Matrix is : 

 [[141   9   0   0]
 [ 35  88  27   0]
 [  0  23 112  15]
 [  0   0  21 129]]


In [156]:
print("The Classification Report is : \n\n", classification_report ( y_test, y_pred))

The Classification Report is : 

               precision    recall  f1-score   support

           0       0.80      0.94      0.87       150
           1       0.73      0.59      0.65       150
           2       0.70      0.75      0.72       150
           3       0.90      0.86      0.88       150

   micro avg       0.78      0.78      0.78       600
   macro avg       0.78      0.78      0.78       600
weighted avg       0.78      0.78      0.78       600



### 7. Decision Tree with GridSearchCV

In [157]:
from sklearn.model_selection import GridSearchCV

In [158]:
param_grid = { "criterion"      : ['gini', 'entropy'],    
               "max_features"   : [3, 4, 5,6,7,9,10 ], 
               "max_depth"      : [ 5, 6, 7,8,9,10],
               "splitter"       : ['best', 'random'],
               "min_samples_leaf"  : [ 2,3,4]
            }

In [159]:
optimized_tree = GridSearchCV(ctree, param_grid, scoring = 'accuracy', cv = 7) 

In [160]:
optimized_tree.fit(x_train, y_train)
ctree_final = optimized_tree.best_estimator_
ctree_final

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=7,
            max_features=9, max_leaf_nodes=None, min_impurity_decrease=0.0,
            min_impurity_split=None, min_samples_leaf=3,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=None, splitter='best')

In [161]:
optimized_tree.best_score_

0.8521428571428571

In [162]:
y_pred_cv = ctree_final.predict(x_test)
print("The accuracy score with best estimator is : ", accuracy_score(y_pred_cv, y_test))

The accuracy score with best estimator is :  0.8466666666666667


### 8. Modelling with SVM

In [163]:
from sklearn.svm import SVC

In [164]:
sv = SVC(gamma='scale')
sv

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [165]:
sv.fit(x_train, y_train)
y_pred = sv.predict(x_test)

In [166]:
print("The accuracy score is : ", accuracy_score ( y_test, y_pred))

The accuracy score is :  0.89


### 9. SVC with Grid Search CV

In [167]:
Cs = [0.001, 0.01, 0.1, 1, 10]
gammas = [0.001, 0.01, 0.1, 1]
param_grid = { 'C': Cs ,  'gamma' : gammas }
grid_search_SVC = GridSearchCV( sv , param_grid, cv = 7)

In [168]:
grid_search_SVC.fit(x_train, y_train)
ctree_final = grid_search_SVC.best_estimator_
ctree_final

SVC(C=10, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=0.1, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [169]:
grid_search_SVC.best_score_

0.9428571428571428

In [170]:
y_pred_sv = ctree_final.predict(x_test)
print("The accuracy score is : ", accuracy_score ( y_test, y_pred_sv))

The accuracy score is :  0.9366666666666666
